In [1]:
import pandas as pd
from pathlib import Path
import numpy as np

In [2]:
root_path = Path("/Users/mac/Documents/Amdari/Amdari/Nexora_Health/nexora-caresync-pipeline/data/source")

In [ ]:
df_patients = pd.read_csv(root_path / "patients.csv")

In [39]:
print("Starting Data Validation process")

Starting Data Validation process

In [ ]:
# validate the the expected columns are in the df_patients data source before any data processing or transfrormation is done
# Id, BIRTHDATE, DEATHDATE, SSN, DRIVERS, PASSPORT, PREFIX, FIRST, MIDDLE, LAST, SUFFIX, 
# MAIDEN, MARITAL, RACE, ETHNICITY, GENDER, BIRTHPLACE, ADDRESS, CITY, STATE, COUNTY, FIPS, 
# ZIP, LAT, LON, HEALTHCARE_EXPENSES, HEALTHCARE_COVERAGE, INCOME
print("1. Schema-Level Validation")
df_patients_expected_columns = [
    "Id", "BIRTHDATE", "DEATHDATE", "SSN", "DRIVERS", "PASSPORT", "PREFIX", "FIRST", "MIDDLE", "LAST",
    "SUFFIX", "MAIDEN", "MARITAL", "RACE", "ETHNICITY", "GENDER", "BIRTHPLACE", "ADDRESS", "CITY", "STATE", 
    "COUNTY", "FIPS", "ZIP", "LAT", "LON", "Id",
    "HEALTHCARE_EXPENSES", "HEALTHCARE_COVERAGE", "INCOME"
]

# validate the expected columns are in the df_patients data source
for col in df_patients_expected_columns:
    if col not in df_patients.columns:
        print(f"Column '{col}' is missing from the patients dataframe.")

1. Schema-Level Validation
Column 'BIRTHDATE' is missing from the patients dataframe.
Column 'DEATHDATE' is missing from the patients dataframe.

In [52]:
# Check table row validation
print("2. Table Row Validation")
total = df_patients.shape[0]
if total < 100: #99
    print("Rows not up to the expected value")
else:
    print(f"The total rows to be processed is {total}")

2. Table Row Validation
Rows not up to the expected value

In [32]:
# version 1: create a copy of the original dataframe to avoid modifying it directly
df_patients_cl = df_patients.copy()

In [38]:
df_patients_cl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113 entries, 0 to 112
Data columns (total 28 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Id                   113 non-null    object
 1   BIRTHDATE            113 non-null    object
 2   DEATHDATE            15 non-null     object
 3   SSN                  113 non-null    object
 4   DRIVERS              95 non-null     object
 5   PASSPORT             92 non-null     object
 6   PREFIX               93 non-null     object
 7   FIRST                113 non-null    object
 8   MIDDLE               93 non-null     object
 9   LAST                 113 non-null    object
 10  SUFFIX               2 non-null      object
 11  MAIDEN               36 non-null     object
 12  MARITAL              82 non-null     object
 13  RACE                 113 non-null    object
 14  ETHNICITY            113 non-null    object
 15  GENDER               113 non-null    object
 16  BIRTHPLACE           113 non-null    object
 17  ADDRESS              113 non-null    object
 18  CITY                 113 non-null    object
 19  STATE                113 non-null    object
 20  COUNTY               113 non-null    object
 21  FIPS                 89 non-null     float64
 22  ZIP                  113 non-null    int64
 23  LAT                  113 non-null    float64
 24  LON                  113 non-null    float64
 25  HEALTHCARE_EXPENSES  113 non-null    float64
 26  HEALTHCARE_COVERAGE  113 non-null    float64
 27  INCOME               113 non-null    int64
dtypes: float64(5), int64(2), object(21)
memory usage: 24.8+ KB

In [24]:
# validate the length of characters in the id column of the patients dataframe
for index, row in df_patients_cl.iterrows():
    if row["Id"] is not None and len(row["Id"]) < 36:
        print(f"Row {index}: The length of characters in the Id column is less than 36.")

Row 4: The length of characters in the Id column is less than 36.
Row 9: The length of characters in the Id column is less than 36.
Row 22: The length of characters in the Id column is less than 36.
Row 25: The length of characters in the Id column is less than 36.
Row 29: The length of characters in the Id column is less than 36.

In [25]:
# Trim the ID column to retain only the last elements when splitted by -
df_patients_cl["Id"] = df_patients_cl["Id"].str.split("-").str[-1]

In [27]:
# filter to row 9 and row 22
df_patients_cl.iloc[[4, 9, 22, 25, 29]]

,Id,BIRTHDATE,DEATHDATE,SSN,DRIVERS,PASSPORT,PREFIX,FIRST,MIDDLE,LAST,...,CITY,STATE,COUNTY,FIPS,ZIP,LAT,LON,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE,INCOME
4,c93095,1999-11-19,NaN,999-20-8896,S99914770,X50559547X,Mr.,Jamison785,Garland107,Gusikowski974,...,Sudbury,Massachusetts,Middlesex County,NaN,0,42.374509,-71.470815,54566.70,33506.70,77367
9,9815b8358f20,2018-12-09,NaN,999-80-8119,NaN,NaN,NaN,Reynaldo722,Hung902,Beatty507,...,Swansea,Massachusetts,Bristol County,NaN,0,41.721180,-71.200369,9084.04,14764.49,113192
22,7390a379d13d,2002-08-17,NaN,999-15-6013,S99931406,X43177593X,Mr.,Arturo47,Santiago500,Piña753,...,Randolph,Massachusetts,Norfolk County,25021.0,2368,42.193864,-71.019048,61691.82,1995.31,121679
25,b534833,1969-01-16,NaN,999-59-9404,S99911920,X81818315X,Mrs.,Willa615,Verlie371,Treutel973,...,Boston,Massachusetts,Suffolk County,25025.0,2116,42.333374,-71.062903,1013145.75,350310.66,55480
29,7d3828f7,1978-07-08,NaN,999-66-2243,S99943199,X1795115X,Mrs.,Trena506,Phoebe31,Bernhard322,...,West Springfield,Massachusetts,Hampden County,25013.0,1089,42.131083,-72.617603,222420.12,1550561.65,23701

In [26]:
len('b77f00240d82')

12

In [28]:
# validate the length of characters in the id column of the patients dataframe
for index, row in df_patients_cl.iterrows():
    if row["Id"] is not None and len(row["Id"]) < 12:
        print(f"Row {index}: The length of characters in the Id column is less than 12.")

Row 4: The length of characters in the Id column is less than 12.
Row 25: The length of characters in the Id column is less than 12.
Row 29: The length of characters in the Id column is less than 12.

In [29]:
# filter to row 9 and row 22
df_patients_cl.iloc[[4, 25, 29]]

,Id,BIRTHDATE,DEATHDATE,SSN,DRIVERS,PASSPORT,PREFIX,FIRST,MIDDLE,LAST,...,CITY,STATE,COUNTY,FIPS,ZIP,LAT,LON,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE,INCOME
4,c93095,1999-11-19,NaN,999-20-8896,S99914770,X50559547X,Mr.,Jamison785,Garland107,Gusikowski974,...,Sudbury,Massachusetts,Middlesex County,NaN,0,42.374509,-71.470815,54566.70,33506.70,77367
25,b534833,1969-01-16,NaN,999-59-9404,S99911920,X81818315X,Mrs.,Willa615,Verlie371,Treutel973,...,Boston,Massachusetts,Suffolk County,25025.0,2116,42.333374,-71.062903,1013145.75,350310.66,55480
29,7d3828f7,1978-07-08,NaN,999-66-2243,S99943199,X1795115X,Mrs.,Trena506,Phoebe31,Bernhard322,...,West Springfield,Massachusetts,Hampden County,25013.0,1089,42.131083,-72.617603,222420.12,1550561.65,23701

In [33]:
# validate the date values in the birthdate column of the patients dataframe
for index, row in df_patients_cl.iterrows():
    try:
        pd.to_datetime(row["BIRTHDATE"])
    except ValueError:
        print(f"Row {index}: Invalid date value in the BirthDate column: {row['BIRTHDATE']}")

Row 12: Invalid date value in the BirthDate column: 199-01-28
Row 22: Invalid date value in the BirthDate column: 2002-08--17

In [34]:
# Convert the "BIRTHDATE" column to datetime format, handling errors by coercing invalid formats to NaT (Not a Time).
df_patients_cl["BIRTHDATE"] = pd.to_datetime(df_patients_cl["BIRTHDATE"])

ValueError: time data "1969 07-11" doesn't match format "%Y-%m-%d", at position 1. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [248]:
# convert deathdate to datetime format, handling errors by coercing invalid formats to NaT (Not a Time).
df_patients_cl["DEATHDATE"] = pd.to_datetime(df_patients_cl["DEATHDATE"], errors='coerce')

In [249]:
# drop ssn, drivers, passpor and prefix columns from the dataframe as they are not needed for further analysis.
df_patients_cl.drop(columns=["SSN", "DRIVERS", "PASSPORT", "PREFIX"], inplace=True)

In [250]:
# fill missing values in marital with unknown as it is a categorical variable and we don't want to lose any data.
df_patients_cl["MARITAL"].fillna("Unknown", inplace=True)

/var/folders/nh/kprmp5xn57l72mppyplsnj100000gq/T/ipykernel_9350/1881352881.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_patients_cl["MARITAL"].fillna("Unknown", inplace=True)

In [ ]:
# strip off the numbers in the first, middle and last name columns to retain only the alphabetic characters.
df_patients_cl["FIRST"] = df_patients_cl["FIRST"].str.replace(r'\d+', '', regex=True)
df_patients_cl["LAST"] = df_patients_cl["LAST"].str.replace(r'\d+', '', regex=True)

In [252]:
# combine first, middle and last name columns into a single column called "FULL_NAME"
df_patients_cl["FULL_NAME"] = df_patients_cl[["FIRST", "MIDDLE", "LAST"]].apply(lambda x: ' '.join(x.dropna()), axis=1)

In [253]:
# drop first, middle and last name columns as they are no longer needed after creating the FULL_NAME column.
# drop suffix and maiden name columns as they are not needed for further analysis.
df_patients_cl.drop(columns=["FIRST", "MIDDLE", "LAST", "SUFFIX", "MAIDEN"], inplace=True)

In [254]:
# Replace all missing values of Marital status with unknown as it is a categorical variable and we don't want to lose any data.
df_patients_cl["MARITAL"] = df_patients_cl["MARITAL"].map({"M": "Married", "S": "Single",
                                                            "D": "Divorced", "W": "Widowed","Unknown": "Unknown"})

In [255]:
df_patients_cl.head(2)

,Id,BIRTHDATE,DEATHDATE,MARITAL,RACE,ETHNICITY,GENDER,BIRTHPLACE,ADDRESS,CITY,STATE,COUNTY,FIPS,ZIP,LAT,LON,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE,INCOME,FULL_NAME
0,b77f00240d82,2001-12-29,NaT,Unknown,white,nonhispanic,F,Hudson Massachusetts US,119 King Lock Apt 20,Boston,Massachusetts,Suffolk County,25025.0,2118,42.292643,-71.062912,5891.27,298460.31,11272,Malvina Leonia Rohan
1,54b7b1ad843a,1969-07-11,NaT,Married,white,nonhispanic,F,Conway Massachusetts US,764 Hudson Ferry Suite 54,Milton,Massachusetts,Norfolk County,25021.0,2186,42.272783,-71.043757,189706.47,685859.80,179290,Min McDermott

 print out a list of all unknown marital status that the deathdate is not null, which means the patient is dead but the marital status is unknown.
df_patients_cl[(df_patients_cl["MARITAL"] == "Unknown") & (df_patients_cl["DEATHDATE"].notnull())]

In [256]:
# Standardize the "RACE", "ETHNICITY" columns by converting all values to title case (first letter capitalized) for consistency.
df_patients_cl["RACE"] = df_patients_cl["RACE"].str.title()
df_patients_cl["ETHNICITY"] = df_patients_cl["ETHNICITY"].str.title()

In [257]:
# Map the "GENDER" column values from "M" and "F" to "Male" and "Female" respectively for clarity and consistency
df_patients_cl["GENDER"] = df_patients_cl["GENDER"].map({"M": "Male", "F": "Female"})

In [258]:
# update the birthplace for patient with the Id c93095b90340 to Shanghai  
# Shanghai-Municipality  CN so as to have a consistent format for all the birthplace values.
df_patients_cl.loc[df_patients_cl["Id"] == "c93095b90340", "BIRTHPLACE"] = "Shanghai  Shanghai-Municipality  CN"

In [259]:
df_patients_cl.head(2)

,Id,BIRTHDATE,DEATHDATE,MARITAL,RACE,ETHNICITY,GENDER,BIRTHPLACE,ADDRESS,CITY,STATE,COUNTY,FIPS,ZIP,LAT,LON,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE,INCOME,FULL_NAME
0,b77f00240d82,2001-12-29,NaT,Unknown,White,Nonhispanic,Female,Hudson Massachusetts US,119 King Lock Apt 20,Boston,Massachusetts,Suffolk County,25025.0,2118,42.292643,-71.062912,5891.27,298460.31,11272,Malvina Leonia Rohan
1,54b7b1ad843a,1969-07-11,NaT,Married,White,Nonhispanic,Female,Conway Massachusetts US,764 Hudson Ferry Suite 54,Milton,Massachusetts,Norfolk County,25021.0,2186,42.272783,-71.043757,189706.47,685859.80,179290,Min McDermott

In [260]:
# split the "BIRTHPLACE" column into three separate columns: "BIRTHPLACE_CITY", "BIRTHPLACE_STATE", 
# and "BIRTHPLACE_COUNTRY" by splitting the string on spaces and extracting the respective parts.

df_patients_cl["BIRTHPLACE_CITY"] = df_patients_cl["BIRTHPLACE"].str.split(" ").str[0]
df_patients_cl["BIRTHPLACE_STATE"] = df_patients_cl["BIRTHPLACE"].str.split(" ").str[2]
df_patients_cl["BIRTHPLACE_COUNTRY"] = df_patients_cl["BIRTHPLACE"].str.split(" ").str[4]

In [261]:
df_patients_cl.head(2)

,Id,BIRTHDATE,DEATHDATE,MARITAL,RACE,ETHNICITY,GENDER,BIRTHPLACE,ADDRESS,CITY,...,ZIP,LAT,LON,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE,INCOME,FULL_NAME,BIRTHPLACE_CITY,BIRTHPLACE_STATE,BIRTHPLACE_COUNTRY
0,b77f00240d82,2001-12-29,NaT,Unknown,White,Nonhispanic,Female,Hudson Massachusetts US,119 King Lock Apt 20,Boston,...,2118,42.292643,-71.062912,5891.27,298460.31,11272,Malvina Leonia Rohan,Hudson,Massachusetts,US
1,54b7b1ad843a,1969-07-11,NaT,Married,White,Nonhispanic,Female,Conway Massachusetts US,764 Hudson Ferry Suite 54,Milton,...,2186,42.272783,-71.043757,189706.47,685859.80,179290,Min McDermott,Conway,Massachusetts,US

In [262]:
# drop birthplace column as it is no longer needed after creating the BIRTHPLACE_CITY, BIRTHPLACE_STATE and BIRTHPLACE_COUNTRY columns.
df_patients_cl.drop(columns=["BIRTHPLACE"], inplace=True)

# Rename resident to the city, state and country columns name to have a consistent format for all the birthplace values.
df_patients_cl.rename(columns={"CITY": "RESIDENT_CITY", 
                               "STATE": "RESIDENT_STATE", 
                               "COUNTY": "RESIDENT_COUNTY"}, inplace=True)

In [263]:
# Convert the "FIPS" column to string type to ensure consistency in data type for further analysis.
df_patients_cl['FIPS'] = df_patients_cl['FIPS'].astype(str)

In [264]:
# Read the missing FIPS codes from the CSV file into a DataFrame called fill_fips.
fill_fips = pd.read_csv(root_path / "missing_fips.csv")

In [265]:
fill_fips.head()

              county  fips_code
0  Barnstable County      25001
1     Bristol County      25005
2    Plymouth County      25023
3   Middlesex County      25017
4   Worcester County      25027

In [266]:
# Merge the df_patients_cl DataFrame with the fill_fips DataFrame on the "RESIDENT_COUNTY" column from df_patients_cl and the "county" column from fill_fips.
# For testing purposes, we will only merge the first 10 rows of df_patients_cl with fill_fips to check if the merge is working correctly.
missing_fips = df_patients_cl[["RESIDENT_STATE", "RESIDENT_COUNTY", "FIPS"]]

In [267]:
missing_fips

    RESIDENT_STATE   RESIDENT_COUNTY     FIPS
0    Massachusetts    Suffolk County  25025.0
1    Massachusetts    Norfolk County  25021.0
2    Massachusetts    Norfolk County  25021.0
3    Massachusetts      Essex County  25009.0
4    Massachusetts  Middlesex County      nan
..             ...               ...      ...
108  Massachusetts  Middlesex County  25017.0
109  Massachusetts  Middlesex County  25017.0
110  Massachusetts    Bristol County  25005.0
111  Massachusetts   Plymouth County      nan
112  Massachusetts   Plymouth County  25023.0

[113 rows x 3 columns]

In [268]:
# Merge the missing_fips DataFrame with the fill_fips DataFrame on the "RESIDENT_COUNTY" column from missing_fips and the "county" column from fill_fips.
df_fips = missing_fips.merge(
    fill_fips,
    how='left',
    left_on='RESIDENT_COUNTY',
    right_on='county'
)

In [269]:
df_fips

    RESIDENT_STATE   RESIDENT_COUNTY     FIPS            county  fips_code
0    Massachusetts    Suffolk County  25025.0               NaN        NaN
1    Massachusetts    Norfolk County  25021.0               NaN        NaN
2    Massachusetts    Norfolk County  25021.0               NaN        NaN
3    Massachusetts      Essex County  25009.0      Essex County    25009.0
4    Massachusetts  Middlesex County      nan  Middlesex County    25017.0
..             ...               ...      ...               ...        ...
108  Massachusetts  Middlesex County  25017.0  Middlesex County    25017.0
109  Massachusetts  Middlesex County  25017.0  Middlesex County    25017.0
110  Massachusetts    Bristol County  25005.0    Bristol County    25005.0
111  Massachusetts   Plymouth County      nan   Plymouth County    25023.0
112  Massachusetts   Plymouth County  25023.0   Plymouth County    25023.0

[113 rows x 5 columns]

In [270]:
# Merge the df_patients_cl DataFrame with the fill_fips DataFrame on the "RESIDENT_COUNTY" column from df_patients_cl and the "county" column from fill_fips.
df_patients_cl = df_patients_cl.merge(
    fill_fips,
    how='left',
    left_on='RESIDENT_COUNTY',
    right_on='county'
)

In [271]:
df_patients_cl.head(2)

,Id,BIRTHDATE,DEATHDATE,MARITAL,RACE,ETHNICITY,GENDER,ADDRESS,RESIDENT_CITY,RESIDENT_STATE,...,LON,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE,INCOME,FULL_NAME,BIRTHPLACE_CITY,BIRTHPLACE_STATE,BIRTHPLACE_COUNTRY,county,fips_code
0,b77f00240d82,2001-12-29,NaT,Unknown,White,Nonhispanic,Female,119 King Lock Apt 20,Boston,Massachusetts,...,-71.062912,5891.27,298460.31,11272,Malvina Leonia Rohan,Hudson,Massachusetts,US,NaN,NaN
1,54b7b1ad843a,1969-07-11,NaT,Married,White,Nonhispanic,Female,764 Hudson Ferry Suite 54,Milton,Massachusetts,...,-71.043757,189706.47,685859.80,179290,Min McDermott,Conway,Massachusetts,US,NaN,NaN

In [272]:
# drop county column as it is no longer needed after merging with the fill_fips dataframe.
df_patients_cl.drop(columns=["county"], inplace=True)

In [273]:
df_patients_cl.head(2)

,Id,BIRTHDATE,DEATHDATE,MARITAL,RACE,ETHNICITY,GENDER,ADDRESS,RESIDENT_CITY,RESIDENT_STATE,...,LAT,LON,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE,INCOME,FULL_NAME,BIRTHPLACE_CITY,BIRTHPLACE_STATE,BIRTHPLACE_COUNTRY,fips_code
0,b77f00240d82,2001-12-29,NaT,Unknown,White,Nonhispanic,Female,119 King Lock Apt 20,Boston,Massachusetts,...,42.292643,-71.062912,5891.27,298460.31,11272,Malvina Leonia Rohan,Hudson,Massachusetts,US,NaN
1,54b7b1ad843a,1969-07-11,NaT,Married,White,Nonhispanic,Female,764 Hudson Ferry Suite 54,Milton,Massachusetts,...,42.272783,-71.043757,189706.47,685859.80,179290,Min McDermott,Conway,Massachusetts,US,NaN

In [321]:
# drop the .0 from the FIPS column values to ensure consistency in the format of the FIPS codes.
df_patients_cl["FIPS"] = df_patients_cl["FIPS"].str.replace(r'\.0$', '', regex=True)

In [322]:
# create another version control of df_patients_cl
final_df = df_patients_cl.copy()

In [323]:
final_df["FIPS"].replace("nan", np.nan, inplace=True)

/var/folders/nh/kprmp5xn57l72mppyplsnj100000gq/T/ipykernel_9350/1582324099.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  final_df["FIPS"].replace("nan", np.nan, inplace=True)

In [324]:
final_df.isna().sum()

Id                      0
BIRTHDATE               0
DEATHDATE              98
MARITAL                 0
RACE                    0
ETHNICITY               0
GENDER                  0
ADDRESS                 0
RESIDENT_CITY           0
RESIDENT_STATE          0
RESIDENT_COUNTY         0
FIPS                   24
ZIP                     0
LAT                     0
LON                     0
HEALTHCARE_EXPENSES     0
HEALTHCARE_COVERAGE     0
INCOME                  0
FULL_NAME               0
BIRTHPLACE_CITY         0
BIRTHPLACE_STATE        0
BIRTHPLACE_COUNTRY      0
fips_code              37
dtype: int64

In [325]:
# Replcae the missing values in the "FIPS" column with the corresponding values from the "fips_code" column obtained from the fill_fips DataFrame.
final_df["FIPS"].fillna(final_df["fips_code"], inplace=True)

/var/folders/nh/kprmp5xn57l72mppyplsnj100000gq/T/ipykernel_9350/726619886.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  final_df["FIPS"].fillna(final_df["fips_code"], inplace=True)

In [326]:
final_df.isna().sum()

Id                      0
BIRTHDATE               0
DEATHDATE              98
MARITAL                 0
RACE                    0
ETHNICITY               0
GENDER                  0
ADDRESS                 0
RESIDENT_CITY           0
RESIDENT_STATE          0
RESIDENT_COUNTY         0
FIPS                    0
ZIP                     0
LAT                     0
LON                     0
HEALTHCARE_EXPENSES     0
HEALTHCARE_COVERAGE     0
INCOME                  0
FULL_NAME               0
BIRTHPLACE_CITY         0
BIRTHPLACE_STATE        0
BIRTHPLACE_COUNTRY      0
fips_code              37
dtype: int64

In [327]:
# drop fips_code column as it is no longer needed after filling the missing values in the "FIPS" column.
final_df.drop(columns=["fips_code"], inplace=True)

In [328]:
new_col = [
    "Id", "BIRTHDATE", "DEATHDATE", "FULL_NAME", "MARITAL", "RACE",
    "ETHNICITY", "GENDER", "ADDRESS", "RESIDENT_CITY", "RESIDENT_STATE", "RESIDENT_COUNTY",
    "BIRTHPLACE_CITY", "BIRTHPLACE_STATE", "BIRTHPLACE_COUNTRY", "FIPS", "ZIP", "LAT",
    "LON", "HEALTHCARE_EXPENSES", "HEALTHCARE_COVERAGE", "INCOME"
]

In [329]:
set(final_df.columns) == set(new_col)

True

In [330]:
set(new_col) - set(final_df.columns)

set()

In [331]:
# rearrange the columns of the final_df DataFrame to match the order specified in the new_col list.
final_df = final_df.loc[:, new_col]

In [332]:
final_df.head()

,Id,BIRTHDATE,DEATHDATE,FULL_NAME,MARITAL,RACE,ETHNICITY,GENDER,ADDRESS,RESIDENT_CITY,...,BIRTHPLACE_CITY,BIRTHPLACE_STATE,BIRTHPLACE_COUNTRY,FIPS,ZIP,LAT,LON,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE,INCOME
0,b77f00240d82,2001-12-29,NaT,Malvina Leonia Rohan,Unknown,White,Nonhispanic,Female,119 King Lock Apt 20,Boston,...,Hudson,Massachusetts,US,25025,2118,42.292643,-71.062912,5891.27,298460.31,11272
1,54b7b1ad843a,1969-07-11,NaT,Min McDermott,Married,White,Nonhispanic,Female,764 Hudson Ferry Suite 54,Milton,...,Conway,Massachusetts,US,25021,2186,42.272783,-71.043757,189706.47,685859.80,179290
2,d56a20511339,1997-03-28,NaT,Asa Rene Schroeder,Married,White,Nonhispanic,Male,519 Ziemann Overpass,Franklin,...,Dudley,Massachusetts,US,25021,2038,42.129644,-71.433066,49809.31,2049.70,55723
3,536444ee049b,1973-11-15,NaT,Lewis Kautzer,Single,White,Hispanic,Female,461 Keebler Meadow Apt 13,Danvers,...,Beverly,Massachusetts,US,25009,1923,42.610734,-71.008010,42810.01,1317375.19,188501
4,c93095b90340,1999-11-19,NaT,Jamison Garland Gusikowski,Unknown,Asian,Nonhispanic,Male,886 Kshlerin Passage,Sudbury,...,Shanghai,Shanghai-Municipality,CN,25017.0,0,42.374509,-71.470815,54566.70,33506.70,77367

In [339]:
# rename the columns of the final_df DataFrame to lowercase for a consistent format for all the column names.
final_df.columns = final_df.columns.str.lower()

In [342]:
# load the data into postgres database with the credential nexora as username and password. 
# The database name is nexora and the table name is patients.

import psycopg2
from sqlalchemy import create_engine
conn = psycopg2.connect(
    host="localhost",
    database="nexora_health",
    user="nexora",
    password="nexora_dev"
)

engine = create_engine('postgresql+psycopg2://nexora:nexora_dev@localhost/nexora_health')

final_df.to_sql('patients', engine, if_exists='append', index=False)

113